word_list = [
    'bigger',
    'taller',
    'stronger',
    'tower',
    'towering',
    'antidisestablishmentarianism',
    'integer',
    'williams',
    'luke williams',
    'marching',
    'dormouse',
    'reusable',
    'redundancy',
    'accent',
    'pottery',
    'poetry',
    'arise',
    'island',
    'biology',
    'empirical',
    'highlight',
    'epistemological',
    'charismatic', ]
